[package]
name = "bill-pdf-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
build_html = "2.5.0"
csv = "1.3.0"
headless_chrome = "1.0.15"
html2pdf = "0.7.1"
serde = { version = "1.0.210", features = ["derive"] }
tera = "1.20.0"
toml = "0.8.19"
