unit = "h"
unit_cost = 10.00
kbm = 22
bill_no = "MR0001"
date = "18.09.2024"
deadline = "02.10.2024"

[company]
name = "Ettevõte OÜ"
email = "example@mail.com"
registry_no = "1234"
address = "Aadress 12"
city = "Rakvere"
country = "Eesti"
post_index = "12345"
kmkr = "EE12345"

[client]
name = "Klient AS"
registry_no = "4321"
address = "Aadress 21"
city = "Tallinn"
post_index = "54321"

[phone]
phone_no = "+372 5555 5555"
phone_type = "Telefon"

[account]
bank_name = "Swedbank AS"
iban = "EE1234567890"